blank_issues_enabled: false
contact_links:
  - name: ğŸ’¡ Suggesting Ideas å»ºè®®/çµæ„Ÿ
    url: https://github.com/Rad586/Forget-Me-Not/discussions/categories/ideas
    about: Suggestions go here! åœ¨è®¨è®ºæ¿å—æå‡ºï¼
