blank_issues_enabled: false
contact_links:
  - name: ğŸ’¡ Suggesting Ideas å»ºè®®/çµæ„Ÿ
    url: https://github.com/Rad586/Forget-Me-Not/discussions/categories/ideas
    about: Suggestions go here! åœ¨çµæ„Ÿæ¿å—æå‡ºï¼

  - name: â“ Q&A æé—®/æ”¯æŒ
    url: https://github.com/Rad586/Forget-Me-Not/discussions/categories/q-a
    about: Questions go here! åœ¨Q&Aæ¿å—æå‡ºï¼

  - name: ğŸ’¬ General è®¨è®º
    url: https://github.com/Rad586/Forget-Me-Not/discussions/categories/general
    about: General discussions go here! åœ¨è®¨è®ºæ¿å—æå‡ºï¼
